# Configuration Docker pour l'environnement de travail

services:
  mongo:
    image: mongo:6.0   # image officielle MongoDB
    container_name: my_mongo_new
    restart: "no"
    command: ["--auth"]
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro #pour les utilisateurs
    networks:
      - my_network

  app:
    build: .
    container_name: healthcare_app_new
    restart: "no"
    networks:
      - my_network
    environment:
      - MONGO_URI=${MONGO_URI}
    volumes :
     - ./data:/app/data
    command: python script/main.py
    depends_on:
     - mongo
  
  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: healthcare_tests
    networks:
      - my_network
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - DB_NAME=ma_bd
      - COLLECTION_NAME=patients
    volumes:
      - ./data:/app/data
      - .:/app
    depends_on:
      - mongo

volumes:
  mongo_data:

networks:
  my_network:
    driver: bridge