# Dockerfile.test
FROM python:3.13-slim

# Installer les dépendances système si besoin
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

# Copier le projet
WORKDIR /app
COPY . /app

# Installer les dépendances Python
RUN pip install --no-cache-dir -r requirements.txt

# Par défaut, ne rien lancer
CMD ["pytest", "--maxfail=1", "--disable-warnings", "test/main_test.py"]